In [1]:
import numpy as np


In [3]:
a = np.array([1, 2, 3, 4 ,5])
reversed_arr = a[::-1] #creates elements with reversed order


In [4]:
reversed_arr

array([5, 4, 3, 2, 1])

In [5]:
#reversing 2d array
#For a 2D array,can reverse the array along specific axes. 
#The axes are indexed as
#0 for rows
#1 for columns.

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
#rows
reversed_axis0 = arr[::-1, :]
                

In [6]:
reversed_axis0

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [7]:
#column
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

reversed_axis1 = arr[:, ::-1]

In [8]:
reversed_axis1

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [10]:
#reverse both row and column
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

reversed_axis2 = arr[::-1, ::-1]

In [11]:
reversed_axis2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [21]:
a = np.array([1, 2, 3, 4, 5])
data_type = arr.dtype

In [22]:
data_type

dtype('int64')

In [25]:
#vstack example:-
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Stack arrays vertically
result_vstack = np.vstack((arr1, arr2))
result_vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
#hstack example:-
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Stack arrays horizontally
result_vstack = np.hstack((arr1, arr2))
result_vstack

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [30]:
arr1 = np.array([[1, 2, 3], 
                  [4, 5, 6]])
array_flipped = np.fliplr(arr1)
array_flipped

array([[3, 2, 1],
       [6, 5, 4]])

In [29]:
arr1 = np.array([[1, 2, 3], 
                  [4, 5, 6]])
array_flipped = np.flipud(arr1)
array_flipped

array([[4, 5, 6],
       [1, 2, 3]])

In [31]:
#Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
array = np.random.randint(1, 101, size=(3, 3))
print(array)

[[57 77 71]
 [48 74 76]
 [58 49  4]]


In [35]:
#interchange rows and column
array.T

array([[57, 48, 58],
       [77, 74, 49],
       [71, 76,  4]])

In [38]:
#Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
arr1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [48]:
#Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array
arr2 = np.random.rand(4,4)
arr2

array([[0.71708806, 0.40523869, 0.50595107, 0.84569887],
       [0.22002136, 0.31366228, 0.34300201, 0.10271641],
       [0.38658214, 0.31572458, 0.41488219, 0.91564059],
       [0.10363046, 0.90048105, 0.63677043, 0.16239144]])

In [49]:
arr2 = np.pad(arr2, pad_width=1, mode='constant', constant_values=0)

In [50]:
arr2

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.71708806, 0.40523869, 0.50595107, 0.84569887,
        0.        ],
       [0.        , 0.22002136, 0.31366228, 0.34300201, 0.10271641,
        0.        ],
       [0.        , 0.38658214, 0.31572458, 0.41488219, 0.91564059,
        0.        ],
       [0.        , 0.10363046, 0.90048105, 0.63677043, 0.16239144,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [52]:
#Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
arr3 = np.arange(10, 61, 5) 
arr3

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [53]:
#Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.
strings = np.array(['python', 'numpy', 'pandas'])

uppercase = np.char.upper(strings)
lowercase = np.char.lower(strings)
titlecase = np.char.title(strings)
capitalize = np.char.capitalize(strings)


In [55]:
strings

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [56]:
uppercase

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [57]:
lowercase

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [58]:
titlecase

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [59]:
capitalize

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [60]:
#Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
words = np.array(['hello', 'world', 'numpy', 'array'])
words_spaces = np.char.join(' ', words)

In [61]:
words_spaces

array(['h e l l o', 'w o r l d', 'n u m p y', 'a r r a y'], dtype='<U9')

In [13]:
#Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10, 20, 30], [40, 50, 60]])



In [14]:
add = array1 + array2

In [15]:
add

array([[11, 22, 33],
       [44, 55, 66]])

In [16]:
subs = array1 - array2
subs

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [17]:
div = array1/array2
div

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [18]:
multiply = array1*array2
multiply

array([[ 10,  40,  90],
       [160, 250, 360]])

In [22]:
#Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)

In [26]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
diagonal_elements

array([1., 1., 1., 1., 1.])

In [29]:
#Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers inthis array.
random_array = np.random.randint(0, 1001, size=100)

def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

prime_numbers = [num for num in random_array if is_prime(num)]


In [30]:
prime_numbers

[641, 251, 191, 661, 179, 733, 659, 29, 971, 3]